### ISSUE TITLE
Doesn't compile on old compiler

### ISSUE THREAD

**Issue by wsmoses** [wsmoses/Tapir-compiler-rt#3]
/root/llvm_sources-tapir5.0/llvm/projects/compiler-rt/lib/cilkscale/csanrt.c: In function ‘__csirt_unit_init’:
/root/llvm_sources-tapir5.0/llvm/projects/compiler-rt/lib/cilkscale/csanrt.c:269:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < NUM_FED_TYPES; ++i) {

**Comment by neboat** [comment]
What compiler is being used that leads to this error?  I need to be able to reproduce the issue.
