### ISSUE TITLE
Any User Guide to Cilkscale?

### ISSUE THREAD

**Issue by ivanium** [wsmoses/Tapir-compiler-rt#4]
Hi, 

I am trying to use Cilkscale to measure parallelism of my Open Cilk program and I compiled Tapir/LLVM on my machine. However, I have no idea how to use the Cilkscale in this repository. I found some user guide to Cilkscan on cilk hub (http://cilk.mit.edu/) but there was nothing about Cilkscale on the website. I am trying to find some user guide to Cilkscale but there seems no document in this repository.
I am wondering if there are some materials of the Cilkscale and could you please tell me how to find them if there are any?

Thank you very much!

**Comment by neboat** [comment]
Thanks for asking!  Indeed, the Cilkscale tool and its documentation are both very much works in progress, as shown in the fairly awful user guide for Cilkscale that I'm about to share with you.

You should have a file called `libclang_rt.cilkscale-x86_64.a` in a lib directory where you built Tapir/LLVM, e.g., under `build/lib/clang/5.0.0/lib/linux/`.  That library contains the Cilkscale runtime.  To use it, first compile your Cilk program using the `-fcsi` flag, then link the Cilkscale library into your program.  For the linking step, you will probably need flags such as `-L/path/to/tapir/build/lib/clang/5.0.0/lib/linux -lclang_rt.cilkscale-x86_64`.

When you run your Cilk program, it should report values for the overall work, span, and parallelism of the program.  The work and span values are measured in millions of LLVM IR instructions executed.  As a result, these measurements should be deterministic for an ostensibly deterministic Cilk program.

**Comment by ivanium** [comment]
Thanks, that solves my problem!
Sorry for updating late due to some other projects I am working on.
I appreciate your help very much.
